// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GpsPositionWithSpeed.proto

package com.masyaman.datapack.compare.objects.protobuf;

public final class GpsPositionWithSpeed {
  private GpsPositionWithSpeed() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GpsPositionWithSpeedProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 lat = 1;
    /**
     * <code>required int32 lat = 1;</code>
     */
    boolean hasLat();
    /**
     * <code>required int32 lat = 1;</code>
     */
    int getLat();

    // required int32 lon = 2;
    /**
     * <code>required int32 lon = 2;</code>
     */
    boolean hasLon();
    /**
     * <code>required int32 lon = 2;</code>
     */
    int getLon();

    // required int32 speed = 3;
    /**
     * <code>required int32 speed = 3;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required int32 speed = 3;</code>
     */
    int getSpeed();

    // required int64 ts = 4;
    /**
     * <code>required int64 ts = 4;</code>
     */
    boolean hasTs();
    /**
     * <code>required int64 ts = 4;</code>
     */
    long getTs();
  }
  /**
   * Protobuf type {@code GpsPositionWithSpeedProto}
   */
  public static final class GpsPositionWithSpeedProto extends
      com.google.protobuf.GeneratedMessage
      implements GpsPositionWithSpeedProtoOrBuilder {
    // Use GpsPositionWithSpeedProto.newBuilder() to construct.
    private GpsPositionWithSpeedProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GpsPositionWithSpeedProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GpsPositionWithSpeedProto defaultInstance;
    public static GpsPositionWithSpeedProto getDefaultInstance() {
      return defaultInstance;
    }

    public GpsPositionWithSpeedProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GpsPositionWithSpeedProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lat_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lon_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              speed_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ts_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.internal_static_GpsPositionWithSpeedProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.internal_static_GpsPositionWithSpeedProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto.class, com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto.Builder.class);
    }

    public static com.google.protobuf.Parser<GpsPositionWithSpeedProto> PARSER =
        new com.google.protobuf.AbstractParser<GpsPositionWithSpeedProto>() {
      public GpsPositionWithSpeedProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpsPositionWithSpeedProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GpsPositionWithSpeedProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 lat = 1;
    public static final int LAT_FIELD_NUMBER = 1;
    private int lat_;
    /**
     * <code>required int32 lat = 1;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 lat = 1;</code>
     */
    public int getLat() {
      return lat_;
    }

    // required int32 lon = 2;
    public static final int LON_FIELD_NUMBER = 2;
    private int lon_;
    /**
     * <code>required int32 lon = 2;</code>
     */
    public boolean hasLon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 lon = 2;</code>
     */
    public int getLon() {
      return lon_;
    }

    // required int32 speed = 3;
    public static final int SPEED_FIELD_NUMBER = 3;
    private int speed_;
    /**
     * <code>required int32 speed = 3;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 speed = 3;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    // required int64 ts = 4;
    public static final int TS_FIELD_NUMBER = 4;
    private long ts_;
    /**
     * <code>required int64 ts = 4;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 ts = 4;</code>
     */
    public long getTs() {
      return ts_;
    }

    private void initFields() {
      lat_ = 0;
      lon_ = 0;
      speed_ = 0;
      ts_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lon_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, speed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, ts_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lon_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, speed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, ts_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GpsPositionWithSpeedProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.internal_static_GpsPositionWithSpeedProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.internal_static_GpsPositionWithSpeedProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto.class, com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto.Builder.class);
      }

      // Construct using com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lon_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.internal_static_GpsPositionWithSpeedProto_descriptor;
      }

      public com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto getDefaultInstanceForType() {
        return com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto.getDefaultInstance();
      }

      public com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto build() {
        com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto buildPartial() {
        com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto result = new com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lon_ = lon_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ts_ = ts_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto) {
          return mergeFrom((com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto other) {
        if (other == com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto.getDefaultInstance()) return this;
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLat()) {
          
          return false;
        }
        if (!hasLon()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        if (!hasTs()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.masyaman.datapack.compare.objects.protobuf.GpsPositionWithSpeed.GpsPositionWithSpeedProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 lat = 1;
      private int lat_ ;
      /**
       * <code>required int32 lat = 1;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 lat = 1;</code>
       */
      public int getLat() {
        return lat_;
      }
      /**
       * <code>required int32 lat = 1;</code>
       */
      public Builder setLat(int value) {
        bitField0_ |= 0x00000001;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lat = 1;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0;
        onChanged();
        return this;
      }

      // required int32 lon = 2;
      private int lon_ ;
      /**
       * <code>required int32 lon = 2;</code>
       */
      public boolean hasLon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 lon = 2;</code>
       */
      public int getLon() {
        return lon_;
      }
      /**
       * <code>required int32 lon = 2;</code>
       */
      public Builder setLon(int value) {
        bitField0_ |= 0x00000002;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lon = 2;</code>
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lon_ = 0;
        onChanged();
        return this;
      }

      // required int32 speed = 3;
      private int speed_ ;
      /**
       * <code>required int32 speed = 3;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 speed = 3;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>required int32 speed = 3;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000004;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 speed = 3;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speed_ = 0;
        onChanged();
        return this;
      }

      // required int64 ts = 4;
      private long ts_ ;
      /**
       * <code>required int64 ts = 4;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 ts = 4;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>required int64 ts = 4;</code>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000008;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ts = 4;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ts_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GpsPositionWithSpeedProto)
    }

    static {
      defaultInstance = new GpsPositionWithSpeedProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GpsPositionWithSpeedProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GpsPositionWithSpeedProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GpsPositionWithSpeedProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032GpsPositionWithSpeed.proto\"P\n\031GpsPosit" +
      "ionWithSpeedProto\022\013\n\003lat\030\001 \002(\005\022\013\n\003lon\030\002 " +
      "\002(\005\022\r\n\005speed\030\003 \002(\005\022\n\n\002ts\030\004 \002(\003B0\n.com.ma" +
      "syaman.datapack.compare.objects.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GpsPositionWithSpeedProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GpsPositionWithSpeedProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GpsPositionWithSpeedProto_descriptor,
              new java.lang.String[] { "Lat", "Lon", "Speed", "Ts", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
